# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: praetor
version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy

builds:
  - id: praetor
    main: ./cmd/praetor
    binary: pt
    goos:
      - linux
    goarch:
      - amd64
      - arm64

    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lance-security/praetor/internal/version.Version={{ .Version }}
      - -X github.com/lance-security/praetor/internal/version.Commit={{ .Commit }}
      - -X github.com/lance-security/praetor/internal/version.Date={{ .Date }}

gomod:
  proxy: true
  env:
    - GOPROXY=direct
    - GOSUMDB=off
    - GOPRIVATE=github.com/lance-security/*
    - GONOSUMDB=github.com/lance-security/*

upx:
  - enabled: true
    ids: [praetor]
    goos: [linux]
    goarch: [amd64, arm64]
    compress: best
    lzma: true
    brute: true

archives:
  - id: default
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  abbrev: 7
  groups:
    - title: "Features"
      regexp: "^[Ff]eat"
      order: 0
    - title: "Bug Fixes"
      regexp: "^[Ff]ix"
      order: 1
    - title: "Miscellaneous"
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: lance-security
    name: praetor
  # If set to true, will not auto-publish the release.
  # Note: all GitHub releases start as drafts while artifacts are uploaded.
  # Available only for GitHub and Gitea.
  draft: false

  # Whether to remove existing draft releases with the same name before creating
  # a new one.
  #
  # Only effective if `draft` is set to true.
  # Available only for GitHub.
  replace_existing_draft: false

  # Whether to use an existing draft release as the target release.
  #
  # Available only for GitHub.
  # Since: v2.5.
  use_existing_draft: false

  # Whether to remove an artifact that already exists.
  #
  # Available only for GitHub.
  # This might be a bit expensive (rate-limiting speaking), so it is only done
  # when the upload of an artifact fails with a 422 (which means it already
  # exists in the release).
  # We then grab the list of artifacts from the release, and delete the file
  # that matches the one we're trying to upload.
  # GoReleaser will then retry its upload.
  replace_existing_artifacts: false

  name_template: "{{ .Tag }}"
  header: |
    # Praetor {{ .Version }}

    **Release Date:** {{ .Date }}
    **Latest Included Commit:** {{ .ShortCommit }}
    **Prerelease:** {{ .Prerelease }}
    **Download URL:** {{ .ReleaseURL }}

    ---
  footer: |
    ---

    ## Installation

    Download the binary for your platform from the assets below, optionally verify the checksum, and place the binary in your `$PATH`.

    ```bash
    tar xzf praetor_{{ .Version }}_<os>_<arch>.tar.gz
    sudo mv pt /usr/local/bin/
    ```

    **Verify Checksum:**
    ```bash
    sha256sum -c checksums.txt
    ```

    > We currently only support Linux. If you'd like to add support for another OS, or you just want to help out, we'd be absolutely happy for you contribute in any way!

    ### Resources

    - [Documentation](https://github.com/{{ .Env.GITHUB_REPOSITORY }})
    - [Report Issues](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/issues)
    - [Discussions](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/discussions)
