# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: praetor
version: 2

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy

builds:
  - id: praetor
    main: ./cmd/praetor
    binary: pt
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lance-security/praetor/internal/version.Version={{ .Version }}
      - -X github.com/lance-security/praetor/internal/version.Commit={{ .Commit }}
      - -X github.com/lance-security/praetor/internal/version.Date={{ .Date }}

gomod:
  proxy: false
  env:
    - GOPROXY=direct
    - GOSUMDB=off
    - GOPRIVATE=github.com/lance-security/*
    - GONOSUMDB=github.com/lance-security/*

upx:
  - enabled: true
    ids: [praetor]
    goos: [linux]
    goarch: [amd64, arm64]
    compress: best
    lzma: true
    brute: true

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: lance-security
    name: praetor
  name_template: "{{ .Tag }}"
  footer: |
    Thanks for using Praetor! Report issues at https://github.com/lance-security/praetor/issues
